version: '3.7'

services:
  vuejs:
    container_name: vuejs
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8090:8080"
    volumes:
      - .:/usr/src/app:cached