version: '3.7'

services:
  nuxtjs-app:
    container_name: nuxtjs-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules/
    command: npm run dev
    environment:
      HOST: 0.0.0.0
      APP_ENV: local
      NODE_ENV: local
    extra_hosts:
      - nuxtjs-app.local:127.0.0.1
